#!/usr/bin/env python3
"""Regenerate the Spelling Bee and Letter Boxed word lists.

Outputs (committed, served as-is by the app):
  public/words-bee.js    BEE_WORDS    - every accepted Spelling Bee answer
  public/words-boxed.js  BOXED_VALID  - every word Letter Boxed accepts
                         BOXED_COMMON - common words the daily puzzle's
                                        built-in solution is drawn from

Sources:
  ENABLE word list (public domain Scrabble-style dictionary)
  wordfreq (pip install wordfreq) for word commonness
  LDNOOBW English list to keep offensive words out of answer lists

Usage:  pip install wordfreq && python3 tools/build_words.py
"""

import os
import re
import urllib.request

import wordfreq

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, "tools", ".cache")

ENABLE_URL = "https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt"
BLOCK_URL = (
    "https://raw.githubusercontent.com/LDNOOBW/"
    "List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en"
)

# Words the blocklist catches that are fine in a word game.
ALLOW = {
    "escort", "domination", "fingering", "snatch", "scat", "bastinado",
    "strappado", "figging", "shrimping", "snowballing", "scissoring",
    "throating", "undressing", "intercourse", "eunuch", "fecal", "rectum",
    "grope", "butt", "suck", "sucks", "hardcore", "playboy", "swinger",
}

# Spelling Bee: how common a word must be to count as an answer. NYT only
# accepts reasonably common words; 2.6 on wordfreq's Zipf scale keeps
# everyday vocabulary while dropping Scrabble-only obscurities.
BEE_MIN_ZIPF = 2.6
# Letter Boxed: the generator builds each daily puzzle around a two-word
# solution from this (more common) pool so the intended answer is fair.
BOXED_COMMON_MIN_ZIPF = 3.3


def fetch(url, name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, name)
    if not os.path.exists(path):
        urllib.request.urlretrieve(url, path)
    with open(path) as f:
        return [line.strip().lower() for line in f if line.strip()]


def main():
    enable = [w for w in fetch(ENABLE_URL, "enable1.txt") if re.fullmatch(r"[a-z]+", w)]
    blocked = set(fetch(BLOCK_URL, "blocklist.txt")) - ALLOW

    def zipf(w):
        return wordfreq.zipf_frequency(w, "en")

    # Spelling Bee never uses S (same as NYT, which keeps plurals out), so
    # any word containing S can never be an answer.
    bee = sorted(
        w for w in enable
        if len(w) >= 4 and "s" not in w and len(set(w)) <= 7
        and w not in blocked and zipf(w) >= BEE_MIN_ZIPF
    )

    # Letter Boxed: consecutive letters must sit on different sides, so a
    # doubled letter ("ll", "ee") can never be played - drop those words.
    no_double = [w for w in enable if len(w) >= 3 and not re.search(r"(.)\1", w)]
    boxed_valid = sorted(w for w in no_double if len(set(w)) <= 12)
    boxed_common = sorted(
        w for w in boxed_valid
        if w not in blocked and 3 <= len(w) <= 10 and zipf(w) >= BOXED_COMMON_MIN_ZIPF
    )

    header = "// Generated by tools/build_words.py - do not edit by hand.\n"
    with open(os.path.join(ROOT, "public", "words-bee.js"), "w") as f:
        f.write(header)
        f.write('const BEE_WORDS = "%s".split(" ");\n' % " ".join(bee))
    with open(os.path.join(ROOT, "public", "words-boxed.js"), "w") as f:
        f.write(header)
        f.write('const BOXED_VALID = "%s".split(" ");\n' % " ".join(boxed_valid))
        f.write('const BOXED_COMMON = "%s".split(" ");\n' % " ".join(boxed_common))

    print(f"bee answers: {len(bee)}")
    print(f"boxed valid: {len(boxed_valid)}, boxed common: {len(boxed_common)}")


if __name__ == "__main__":
    main()
